[JBMAR-241] Support serialization of java record type
jboss-remoting/jboss-marshalling pull request #104
Opened 2022-09-26 08:13 UTC by rmartinc

Issue: https://issues.redhat.com/browse/JBMAR-241

Adding record serialization/deserialization to the implementations. Main changes:

* I have used versioning to add java-16, so now api needs jdk-16 as the minimum jdk version (the first version that uses records without the preview condition). If you prefer to not have this requirement, using a full reflection solution and maintaining jdk-9 minimum, just let me know.

* The main pom reduced minimum version from 9 to 8. This was done because testing previous versions is easier this way, you can just compile everything with 17 (for example) and then only the test folder can be executed with java 11 or 1.8 directly (record tests are just not compiled/executed).

```bash
export JAVA_HOME=/path/to/jdk-17
mvn clean install
cd tests
export JAVA_HOME=/path/to/jdk-1.8.0
mvn clean test
```

* Changes done in api, river and serial (un)marshallers to include records.
* New test and factory classes to check the records marshalling and unmarshalling. If you think more tests are needed just let me know too.

@ropalka I think the PR is ready for review.

Thanks!

2022-09-27 11:19 UTC, ropalka requested changes
I identified just three minor issues @rmartinc

2022-09-27 11:19 UTC, ropalka commented on serial/src/main/java/org/jboss/marshalling/serial/SerialMarshaller.java
> +        }
Why here are two enhanced for loops? Those could be merged into one or am I missing something?

2022-09-27 11:19 UTC, ropalka commented on serial/src/main/java/org/jboss/marshalling/serial/SerialUnmarshaller.java
> +        }
Same as above. Why here are two enhanced for loops? Those could be merged into one or am I missing something?

2022-09-27 12:31 UTC, rmartinc commented on api/src/main/java/org/jboss/marshalling/reflect/SerializableClass.java
> +    public SerializableField getSerializableField(String name) {
Uuups! You are right! I think that I used it before and I forgot to remove it. Fixed!

2022-09-27 14:05 UTC, ropalka commented on serial/src/main/java/org/jboss/marshalling/serial/SerialMarshaller.java
> +        }
Thanks for clarification Ricardo.

2022-09-27 14:06 UTC, ropalka approved these changes

2022-09-27 22:30 UTC, merged

2022-09-28 13:00 UTC, ropalka commented
Thanks @rmartinc !